[env:esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32dev
framework = arduino
lib_deps = HomeSpan
board_build.partitions = partitions_4M.csv

[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
lib_deps = HomeSpan
board_build.partitions = partitions_4M.csv

[env:esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = seeed_xiao_esp32c3
framework = arduino
lib_deps = HomeSpan
board_build.partitions = partitions_4M.csv
