[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = homespan/HomeSpan@^2.1.8

[env:esp32s3]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino

lib_deps =
HomeSpan

[env:esp32c3]
platform = espressif32
board = eeed_xiao_esp32c3
framework = arduino

lib_deps =
HomeSpan
